### ISSUE TITLE
Disabling -L/usr/lib64 -L/usr/lib32 on macos

### ISSUE THREAD

**Issue by JohannesMP** [premake/premake-core#473]
When compiling a gmake project configured for 32 or 64 bit on mac (tested on Mac OS 10.10.5) I always see this warning, when using either gcc or clang:

    ld: warning: directory not found for option '-L/usr/lib32'

and

    ld: warning: directory not found for option '-L/usr/lib64'
 
which is the result of [this code](https://github.com/premake/premake-core/blob/5bbc06f4b63120718e2e54755fdbaab3065ab9a0/src/tools/gcc.lua#L238-L241).

-----

Since mac os only has `/usr/lib` and never `/usr/lib32` or `/usr/lib64` (as far as I can tell), the code should be modified to account for that so that this warning no longer occurs.

**Comment by tbelaire** [comment]
Here's some sed scripts to make it easier.

```
sed -i -- 's%-Wl,--end-group%%' *.make
sed -i -- 's%-Wl,--start-group%%' *.make
sed -i -- 's%-L/usr/lib64%%' *.make
```

**Comment by samsinsane** [comment]
Closing as this issue should be resolved in master due to #543.

**Comment by speeder** [comment]
I am using the newest version on the site, and this bug still exists.
