### ISSUE TITLE
Seemly there is no way to tell Premake my files are C11

### ISSUE THREAD

**Issue by speeder** [premake/premake-core#642]
I noticed my C11 code break horribly when I compile with premake, despite compiling fine if I use the compiler directly.

Then I realized is because Clang and GCC, both default to C11 right now, but premake seemly has only C89 and C99 flags, and forces them to use such (or seemly use C++ on C code?)

**Comment by tvandijck** [comment]
I think this was fixed in here: https://github.com/premake/premake-core/pull/623

**Comment by speeder** [comment]
It wasn't, at least when reading the commit changes... it added only explicit c89 and c99 flags.

**Comment by speeder** [comment]
I saw the change merged, it makes the C89, C99 and C11 flags trigger the compiler flag -gnu89, gnu99 and gnu11

But gnu* is different from the standard* version (even if not by much, but is still not the same thing).

So, what is the proper way to tell that I want C11, not GNU11?

**Comment by samsinsane** [comment]
@tvandijck mentioned he would be attempting to make this a proper API this month, so hopefully he gets a chance to do that and can support the standard set of options (`c*`, `gnu*`, `c++*` and `gnu++*`, preferably without GNU as the default).

In the meantime, you can emit the command line flag manually via `buildoptions { "-std=c11" }` until such an API exists.

**Comment by speeder** [comment]
@samsinsane I see, I tested it here, it worked, thanks!
